### PR TITLE
fix: coredns crash issue.

### LINKED ISSUE #2074: BUG: k8s 1.25 coreDNS error
### Sealos Version

v:4.1.4-rc1

### How to reproduce the bug?

```
$ sealos run labring/kubernetes:v1.25.0 labring/helm:v3.8.2 labring/calico:v3.24.1 \
     --masters 192.168.64.2,192.168.64.22,192.168.64.20 \
     --nodes 192.168.64.21,192.168.64.19 -p [your-ssh-passwd]
```
```
kubectl get pod -A
kube-system        coredns-565d847f94-5b2wt                   0/1     CrashLoopBackOff   2271 (4m1s ago)   8d
kube-system        coredns-565d847f94-jtw9f                   0/1     CrashLoopBackOff   2271 (88s ago)    8d
```

```
root@laf-test-master1:/home/ubuntu# kubectl logs coredns-565d847f94-5b2wt  -n kube-system
.:53
[INFO] plugin/reload: Running configuration SHA512 = 591cf328cccc12bc490481273e738df59329c62c0b729d94e8b61db9961c2fa5f046dd37f1cf888b953814040d180f52594972691cd6ff41be96639138a43908
CoreDNS-1.9.3
linux/amd64, go1.18.2, 45b0a11
[FATAL] plugin/loop: Loop (127.0.0.1:58433 -> :53) detected for zone ".", see https://coredns.io/plugins/loop#troubleshooting. Query: "HINFO 8407610317041155683.2379619262876814132."
```

k8s version 1.24 won't have this problem
```
sealos run labring/kubernetes:v1.24.0 labring/helm:v3.8.2 labring/calico:v3.22.1
```
### What is the expected behavior?

_No response_

### What do you see instead?

_No response_

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by fengxsong**
Signed-off-by: fengxsong <fengxsong@outlook.com>

Set kubelet.ResolverConfig to nil. fix #2074  #1620

### CODE REVIEW

File: pkg/runtime/kubeadm_config.go [hunk 1]
```diff
@@ -210,9 +212,35 @@ func TypeConversion(raw []byte, kind string) (interface{}, error) {
 		return nil, err
 	}
 	scheme.Default(obj)
+	OverrideDefaults(obj)
 	return obj, nil
 }
 
+func overrideKubeletDefaults(i interface{}) {
```
Comment (cuisongliu) [inline pkg/runtime/kubeadm_config.go:219]:
```
var scheme = k8sruntime.NewScheme()
var (
	localSchemeBuilder = &kubeletconfigv1beta1.SchemeBuilder
)

func init() {
	utilruntime.Must(kubeadmv1beta2.AddToScheme(scheme))
	utilruntime.Must(kubeadmv1beta3.AddToScheme(scheme))
	utilruntime.Must(localSchemeBuilder.AddToScheme(scheme))
	utilruntime.Must(proxyconfig.AddToScheme(scheme))
	localSchemeBuilder.Register(kubeletconfig.RegisterDefaults, override)
}

func override(scheme *k8sruntime.Scheme) error {
	scheme.AddTypeDefaultingFunc(&kubelet.KubeletConfiguration{}, func(obj interface{}) {})
	return nil
}

```

this is better ?

Comment (zzjin) [reply pkg/runtime/kubeadm_config.go:219]: At my option, `fn func(interface{})` have two cons:
1. not return any error message
2. interface can be changed to any type and not under our control(like go 1.19 add generic types.)
and reflect with ptr should use with carful caution.

```golang
_ = kubeadmv1beta2.RegisterDefaults(scheme) 
_ = kubeadmv1beta3.RegisterDefaults(scheme)
_ = proxyconfig.RegisterDefaults(scheme)
```
with error handle will do better.

Comment (fengxsong) [reply pkg/runtime/kubeadm_config.go]: Utilruntime.Must is used for error handling. I've make a little change in the recent commit, IMO, we don't need to make so much changes.

**Review by cuisongliu — APPROVED** [review]
