### PR TITLE
feature(main): fix delete add node and skip error

### LINKED ISSUE #1028: delete node if port not 22
1. sealos delete port 2822 for node can't delete,sealos check port is 22
2. sealos delete node (192.168.64.8:2822) port not 22 save Clusterfile is 192.168.64.8:2822:2822
3. sealos 5 node(192.168.64.1:2822...192.168.64.5:2822) , delete node 192.168.64.5:2822, but `kubectl get node` 192.168.64.5 is not ready , 192.168.64.2 is delete by sealos

### PR DESCRIPTION
**Pull request by cuisongliu**
fix #1028

### CODE REVIEW

File: pkg/apply/scale.go [hunk 1]
```diff
@@ -165,6 +167,20 @@ func deleteNodes(cluster *v2.Cluster, scaleArgs *RunArgs) error {
...
+	hostsSet := sets.NewString()
+
+	for _, node := range cluster.Spec.Hosts {
+		hostsSet.Insert(node.IPS...)
+	}
+
+	for _, node := range strings.Split(scaleArgs.Nodes, ",") {
+		targetIP, targetPort := iputils.GetHostIPAndPortOrDefault(node, defaultPort)
+		if !hostsSet.Has(fmt.Sprintf("%s:%s", targetIP, targetPort)) {
+			return fmt.Errorf(" Parameter error: delete must be in cluster hosts ips！")
```
Comment (fanux) [inline pkg/apply/scale.go:180]: Parameter error: to delete IP %s must in cluster IP list, ip

File: pkg/runtime/reset.go [hunk 2]
```diff
@@ -71,19 +70,19 @@ func (k *KubeadmRuntime) resetNode(node string) error {
 	logger.Info("start to reset node: %s", node)
 	if err := k.sshCmdAsync(node, fmt.Sprintf(RemoteCleanMasterOrNode, vlogToStr(k.vlog), k.getEtcdDataDir()),
 		RemoveKubeConfig, DeleteImageShimCMD(k.getContentData().RootFSPath())); err != nil {
-		return fmt.Errorf("exec node clean in sealos failed %v", err)
+		logger.Error("exec node clean in sealos failed %v", err)
```
Comment (fanux) [inline pkg/runtime/reset.go:73]: failed to clean node,  exec command %s failed, %v , command, err

**Review by fanux — APPROVED** [review]
