### PR TITLE
fix(main): bootstrap registry before all step

### LINKED ISSUE #2741: BUG: run error if /var/lib/registry/registry exists
### Sealos Version

main

### How to reproduce the bug?

```
error Applied to cluster error: failed to make link: failed to execute command(ln -s /var/lib/sealos/data/default/rootfs/registry /var/lib/registry) on host(192.168.64.89:22): output(ln: failed to create symbolic link '/var/lib/registry/registry': File exists), error(Process exited with status 1)
```

### What is the expected behavior?

_No response_

### What do you see instead?

_No response_

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by cuisongliu**
Closes #2741

### CODE REVIEW

File: pkg/bootstrap/bootstrap.go [hunk 1]
```diff
@@ -27,95 +27,90 @@ import (
 type Phase string
 
 const (
-	Preflight Phase = "preflight"
-	Init      Phase = "init"
-	Addon     Phase = "addon"
+	Preflight  Phase = "preflight"
```
Comment (fengxsong) [inline pkg/bootstrap/bootstrap.go:30]: Preflight: preflight checks;
Init: initilaization;
Postflight: what does postflight for?

Comment (cuisongliu) [reply pkg/bootstrap/bootstrap.go:30]: Postflight is mainly reserved, and some operations are performed after initialization.

**Review by fengxsong — APPROVED** [review]
