### PR TITLE
fix: generate .kube dir in home dir

### LINKED ISSUE #1320: BUG: .kube directory was not generated in home directory
**Which command or component**

sealos run

**The Description of the bug**

`sealos run` will generated .kube directory **in current working directory instead of home directory**. Thus if we not execute `sealos run` in home directory, kubectl will not work.
Related code: https://github.com/labring/sealos/blob/78b9b7f43d489fe9370bf9add10a8dca59e9f3fb/pkg/runtime/kubeconfig.go#L21-L31
https://github.com/labring/sealos/blob/78b9b7f43d489fe9370bf9add10a8dca59e9f3fb/pkg/ssh/sshcmd.go#L54-L57

### PR DESCRIPTION
**Pull request by gitccl**
Signed-off-by: gitccl <chenchuanle6@gmail.com>
fix #1320

### CODE REVIEW

File: pkg/runtime/kubeconfig.go [hunk 1]
```diff
@@ -18,7 +18,7 @@ package runtime
 
 import "path"
 
-const RemoteCopyKubeConfig = `rm -rf .kube/config && mkdir -p  .kube && cp /etc/kubernetes/admin.conf .kube/config`
+const RemoteCopyKubeConfig = `rm -rf $HOME/.kube/config && mkdir -p  $HOME/.kube && cp /etc/kubernetes/admin.conf $HOME/.kube/config`
```
Comment (cuisongliu) [inline pkg/runtime/kubeconfig.go:21]: Isn‘t it appropriate to use environment variables? We use code to obtain user catalogues.

**Review by cuisongliu — APPROVED** [review]
