### PR TITLE
docs(main): fix gen before pull image and inspect it

### LINKED ISSUE #2069: BUG:  sealos gen unknown kubernetes version
### Sealos Version

v4.1.4-rc1

### How to reproduce the bug?

sealos gen labring/kubernetes:v1.24.0 labring/helm:v3.8.2 labring/calico:v3.22.1 --masters 192.168.64.77 --nodes 192.168.64.78
2022-11-08T22:17:08 error error version format  1.25.0

### What is the expected behavior?

Are we adding a version number to this command parameter, because this command does not actually pull the image, making it impossible to get the real image name?
sealos gen labring/kubernetes:v1.24.0 labring/helm:v3.8.2 labring/calico:v3.22.1 --masters 192.168.64.77 --nodes 192.168.64.78 --version v1.24.0

Or shall we also pull the image at the gen cmd?

### What do you see instead?

_No response_

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by cuisongliu**
close #2069  #2348  #2344

### CODE REVIEW

File: pkg/apply/gen.go [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+		data, err := yaml.MarshalYamlConfigs(objects...)
+		if err != nil {
+			return nil, err
+		}
+		return data, nil
+	}
+	return nil, errors.New("unknown convert kubeadmRuntime error")
+}
+
+func genImageInfo(imageName []string) (*v1beta1.MountImage, error) {
```
Comment (fengxsong) [inline pkg/apply/gen.go:74]: IMO, `gen` command does not need to do anything with the image list.

Comment (cuisongliu) [reply pkg/apply/gen.go:74]: Required, otherwise the image version number cannot be obtained. gen reports an error directly

File: pkg/apply/gen.go [hunk 2]
```diff
@@ -27,16 +36,53 @@ func NewClusterFromGenArgs(imageName []string, args *RunArgs) ([]interface{}, er
...
 	}
-	kubeadmcfg := &runtime.KubeadmConfig{}
-	if err := kubeadmcfg.Merge(""); err != nil {
+
+	img, err := genImageInfo(imageName)
+	if err != nil {
+		return nil, err
+	}
+	if img.Type != v1beta1.RootfsImage {
+		return nil, fmt.Errorf("input first image %s is not rootfs image", imageName)
```
Comment (fanux) [inline pkg/apply/gen.go:45]: user maybe don't know what is rootfs image. rootfs image -> kubernetes image?

**Review by fanux — APPROVED** [review]
