### PR TITLE
fix(main): fix merge and hidden flags

### LINKED ISSUE #2653: BUG: merge timeout
### Sealos Version

4.1.5-rc3

### How to reproduce the bug?

```
cuisongliu@cuisongliu:~/Downloads$ sealos merge -t k8s-docker:1.25   labring/kubernetes-docker:v1.25-arm64 ghcr.io/labring/sealos-patch:dev-arm64
Resolving "labring/kubernetes-docker" using unqualified-search registries (/home/cuisongliu/.config/containers/registries.conf)
Trying to pull docker.io/labring/kubernetes-docker:v1.25-arm64...
Getting image source signatures
Copying blob e53ba7f551d3 done  
Copying blob b9ab1c367f26 done  
Copying blob cd967681830e done  
Copying blob 0c04682f13b0 done  
Copying config 2de12fd740 done  
Writing manifest to image destination
Storing signatures
WARNING: image platform ({arm64 linux  [] }) does not match the expected platform ({amd64 linux  [] })
Trying to pull ghcr.io/labring/sealos-patch:dev-arm64...
Getting image source signatures
Copying blob e79301806147 done  
Copying config d2def9fc93 done  
Writing manifest to image destination
Storing signatures
WARNING: image platform ({arm64 linux  [] }) does not match the expected platform ({amd64 linux  [] })
2023-02-23T14:23:38 warn save-image is disabled, skip pulling images
STEP 1/29: FROM scratch
STEP 2/29: MAINTAINER labring
STEP 3/29: LABEL auth="auth.sh \$registryDomain \$registryPort \$registryUsername \$registryPassword \$sandboxImage"
STEP 4/29: LABEL check="check.sh \$registryData"
STEP 5/29: LABEL clean="clean.sh && bash clean-cri.sh \$criData \$criDockerdData"
STEP 6/29: LABEL clean-registry="clean-registry.sh \$registryData \$registryConfig"
STEP 7/29: LABEL image="localhost:5000/labring/lvscare:1c09839-arm64"
STEP 8/29: LABEL init="init-cri.sh && bash init.sh"
STEP 9/29: LABEL init-registry="init-registry.sh \$registryData \$registryConfig"
STEP 10/29: LABEL io.buildah.version="1.26.1"
STEP 11/29: LABEL org.opencontainers.image.description="kubernetes-v1.25.6 container image"
STEP 12/29: LABEL org.opencontainers.image.licenses="MIT"
STEP 13/29: LABEL org.opencontainers.image.source="https://github.com/labring-actions/cache"
STEP 14/29: LABEL sealos.io.type="rootfs"
STEP 15/29: LABEL sealos.io.version="v1beta1"
STEP 16/29: LABEL version="v1.25.6"
STEP 17/29: LABEL vip="\$defaultVIP"
STEP 18/29: ENV criData=/var/lib/docker
STEP 19/29: ENV criDockerdData=/var/lib/cri-dockerd
STEP 20/29: ENV defaultVIP=10.103.97.2
STEP 21/29: ENV registryConfig=/etc/registry
STEP 22/29: ENV registryData=/var/lib/registry
STEP 23/29: ENV registryDomain=sealos.hub
STEP 24/29: ENV registryPassword=passw0rd
STEP 25/29: ENV registryPort=5000
STEP 26/29: ENV registryUsername=admin
STEP 27/29: ENV sandboxImage=pause:3.8
STEP 28/29: COPY --from=labring/kubernetes-docker:v1.25-arm64  . .
Resolving "labring/kubernetes-docker" using unqualified-search registries (/home/cuisongliu/.config/containers/registries.conf)
Trying to pull docker.io/labring/kubernetes-docker:v1.25-arm64...
WARN[0422] Failed, retrying in 2s ... (1/3). Error: initializing source docker://labring/kubernetes-docker:v1.25-arm64: Get "https://auth.docker.io/token?account=cuisongliu&scope=repository%3Alabring%2Fkubernetes-docker%3Apull&service=registry.docker.io": read tcp 127.0.0.1:56370->127.0.0.1:7890: read: connection reset by peer 
Getting image source signatures
Copying blob b9ab1c367f26 skipped: already exists  
Copying blob e53ba7f551d3 skipped: already exists  
Copying blob 0c04682f13b0 skipped: already exists  
Copying blob cd967681830e skipped: already exists  
Copying config 2de12fd740 done  
Writing manifest to image destination
Storing signatures
WARNING: image platform ({arm64 linux  [] }) does not match the expected platform ({amd64 linux  [] })
STEP 29/29: COPY --from=ghcr.io/labring/sealos-patch:dev-arm64  . .
Trying to pull ghcr.io/labring/sealos-patch:dev-arm64...
Getting image source signatures
Copying blob e79301806147 skipped: already exists  
Copying config d2def9fc93 done  
Writing manifest to image destination
Storing signatures
WARNING: image platform ({arm64 linux  [] }) does not match the expected platform ({amd64 linux  [] })
COMMIT k8s-docker:1.25
Getting image source signatures
Copying blob 32e8880e7530 done  
Copying config 9dc096660d done  
Writing manifest to image destination
Storing signatures
--> 9dc096660d7
[Warning] one or more build args were not consumed: [TARGETARCH TARGETOS TARGETPLATFORM]
Successfully tagged localhost/k8s-docker:1.25
9dc096660d7e3e14036aa41e8dd9ff09230e3ff543251f07ef812e3209e7ded2

```

### What is the expected behavior?

_No response_

### What do you see instead?

_No response_

### Operating environment

```markdown
- Sealos version:
- Docker version:
- Kubernetes version:
- Operating system:
- Runtime environment:
- Cluster size:
- Additional information:
```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by cuisongliu**
Closes #2653

### CODE REVIEW

File: pkg/buildah/common.go [hunk 1]
```diff
@@ -63,33 +56,84 @@ func setDefaultFlagsWithSetters(c *cobra.Command, setters ...func(*cobra.Command
 	}
 	return nil
 }
+func markFlagsHiddenPlatform() []string {
```
Comment (fengxsong) [inline pkg/buildah/common.go:59]: suggestion:

var hiddenFlagsAboutPlatform = []string{"arch", "os", "os-feature", "os-version", "variant"}

same as hiddenFlagsInBuild..

File: pkg/buildah/merge.go [hunk 2]
```diff
@@ -112,21 +120,23 @@ func newMergeCommand() *cobra.Command {
 	flags.SetNormalizeFunc(buildahcli.AliasFlags)
 	bailOnError(markFlagsHidden(flags, "save-image"), "")
 	bailOnError(markFlagsHidden(flags, "tls-verify"), "")
+	bailOnError(markFlagsHidden(flags, markFlagsHiddenPlatform()...), "")
```
Comment (fengxsong) [inline pkg/buildah/merge.go:123]: append(hiddenFlagsAboutPlatform, hiddenFlagsInBuild...)...

File: pkg/utils/maps/maps.go [hunk 3]
```diff
@@ -30,6 +30,15 @@ func MapToString(data map[string]string) string {
 	return strings.Join(result, ",")
 }
 
+func MapToStringBySpilt(data map[string]string, spilt string) string {
+	result := make([]string, 0)
```
Comment (fengxsong) [inline pkg/utils/maps/maps.go:34]: result := make([]string, len(data))

**Review by fengxsong — APPROVED** [review]
SGTM
